import tkinter as tk
from tkinter import filedialog, ttk
import csv
import os
import logging
from datetime import datetime

# Initialize a module-specific logger
logger = logging.getLogger(__name__)

class CanLogParser:
    """
    Engine for decoding CSV logs generated by IXXAT canAnalyser.
    Extracts payloads and organizes them by CAN ID, associating a relative time axis.
    """
    def __init__(self):
        # Structure: { "0x320": {"time": [0.0, 0.01, ...], "data": [[0x00, 0x53...], ...]} }
        self.log_data: dict[str, dict[str, list]] = {}
        self.total_messages = 0

    def load_csv(self, filepath: str) -> bool:
        logger.info(f"Starting log file parsing: {filepath}")
        self.log_data.clear()
        self.total_messages = 0
        start_time_obj = None

        try:
            with open(filepath, mode='r', encoding='utf-8') as file:
                # IXXAT CSV uses semicolon as delimiter
                reader = csv.DictReader(file, delimiter=';')
                
                for row in reader:
                    raw_id = row.get('ID (hex)')
                    raw_time = row.get('Time (abs)')
                    raw_data = row.get('Data (hex)')
                    
                    # Ignore empty or malformed rows
                    if not raw_id or not raw_time or not raw_data:
                        continue
                        
                    # 1. ID Normalization (from "320" to "0x320")
                    can_id = f"0x{raw_id.strip().upper()}"
                    
                    # 2. Calculate relative time in seconds (X-axis for plots)
                    try:
                        time_obj = datetime.strptime(raw_time.strip(), "%H:%M:%S.%f")
                        if start_time_obj is None:
                            start_time_obj = time_obj
                        
                        delta = time_obj - start_time_obj
                        relative_time_sec = delta.total_seconds()
                    except ValueError:
                        # If time format parsing fails, skip the row
                        continue

                    # 3. Convert hexadecimal payload into a list of integers (Bytes)
                    # "00 53 32" -> [0, 83, 50]
                    try:
                        byte_list = [int(b, 16) for b in raw_data.strip().split()]
                    except ValueError:
                        continue

                    # 4. Insertion into the structured dictionary
                    if can_id not in self.log_data:
                        self.log_data[can_id] = {"time": [], "data": []}
                        
                    self.log_data[can_id]["time"].append(relative_time_sec)
                    self.log_data[can_id]["data"].append(byte_list)
                    self.total_messages += 1

            logger.info(f"Parsing completed: {self.total_messages} messages processed across {len(self.log_data)} distinct IDs.")
            return True
            
        except Exception as e:
            logger.error(f"Critical error while reading the CSV: {e}", exc_info=True)
            return False


class CsvLoaderUI:
    """
    Standalone Graphical User Interface to test CSV file loading.
    Displays a summary of the acquired data.
    """
    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("IXXAT CSV Log Loader")
        self.root.geometry("500x400")
        
        self.parser = CanLogParser()
        self.setup_ui()

    def setup_ui(self):
        # --- Top Frame: File Selection ---
        top_frame = tk.Frame(self.root)
        top_frame.pack(side=tk.TOP, fill=tk.X, padx=10, pady=10)
        
        self.btn_load = tk.Button(top_frame, text="Load IXXAT CSV", command=self.open_file_dialog)
        self.btn_load.pack(side=tk.LEFT)
        
        self.lbl_file = tk.Label(top_frame, text="No file selected", fg="gray")
        self.lbl_file.pack(side=tk.LEFT, padx=10)
        
        # --- Middle Frame: Results ---
        mid_frame = tk.Frame(self.root)
        mid_frame.pack(side=tk.TOP, fill=tk.BOTH, expand=True, padx=10, pady=5)
        
        # Treeview to show how many messages exist for each ID
        self.tree = ttk.Treeview(mid_frame, columns=("ID", "Messages"), show="headings")
        self.tree.heading("ID", text="CAN ID")
        self.tree.heading("Messages", text="Number of Messages (Samples)")
        self.tree.column("ID", anchor=tk.CENTER)
        self.tree.column("Messages", anchor=tk.CENTER)
        self.tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        
        scrollbar = ttk.Scrollbar(mid_frame, orient="vertical", command=self.tree.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.tree.configure(yscrollcommand=scrollbar.set)

    def open_file_dialog(self):
        filepath = filedialog.askopenfilename(
            title="Select IXXAT CSV log",
            filetypes=(("CSV files", "*.csv"), ("All files", "*.*"))
        )
        
        if filepath:
            self.lbl_file.config(text=os.path.basename(filepath), fg="black")
            success = self.parser.load_csv(filepath)
            
            if success:
                self.populate_results()

    def populate_results(self):
        # Clear the table
        for item in self.tree.get_children():
            self.tree.delete(item)
            
        # Insert results sorted by ID
        for can_id in sorted(self.parser.log_data.keys()):
            num_messages = len(self.parser.log_data[can_id]["time"])
            self.tree.insert("", tk.END, values=(can_id, num_messages))
            
        logger.debug("Results table updated.")

if __name__ == "__main__":
    # Basic logging config for standalone execution
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - [%(levelname)s] - %(name)s - %(message)s')
    # Launch in standalone mode to test ONLY this component
    root = tk.Tk()
    app = CsvLoaderUI(root)
    root.mainloop()